baseURL: 'https://donihalim.id'
languageCode: 'en-us'
title: 'Doni Halim'
enableGitInfo: true

markup:
  goldmark:
    renderer:
      unsafe: true

disableKinds:
  - taxonomy
  - term

permalinks:
  page:
    blog: /blog/:year/:month/:day/:slug/

outputs:
  home:
    - html

  page:
    - html

  section:
    - html
    - rss
    - atom

mediaTypes:
  application/atom+xml:
    suffixes:
      - xml

outputFormats:
  rss:
    mediaType: application/xml
    baseName: rss

  atom:
    mediaType: application/atom+xml
    basename: atom

params:
  description: 'Personal website of Doni Halim'
  author:
    name: 'Doni Halim'
    email: 'donihalim@protonmail.com'

